site_name: ICGS112 Notes
theme:
  name: material
  palette:
    scheme: slate  # dark mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Midterm:
      - Lecture Notes: midterm-lecture.md
      - Questions: midterm-questions.md
  - Final:
      - Lecture Notes: final-lecture.md
      - Questions: final-questions.md

