site_name: ICGS112 NOTES
theme:
  name: 
  palette:
    scheme: slate  # dark mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight
nav:
  - Home: index.md
  - Lecture Notes: lecture.md
  - Exam Questions: questions.md

