site_name: ICGS112 NOTES
theme:
  name: material
  palette:
    scheme: slate  # dark mode
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight
nav:
  - Home: index.md
  - Midterm lecture: midterm-lecture.md
  - Midterm questions: midterm-questions.md
  - Final lecture: final-lecture.md
  - Final questions: final-questions.md
